#define BTSK_FORWARD SDLK_w
#define BTSK_BACK    SDLK_s
#define BTSK_LEFT    SDLK_a
#define BTSK_RIGHT   SDLK_d
#define BTSK_JUMP    SDLK_SPACE
#define BTSK_CROUCH  SDLK_LCTRL

#define BTSK_LOOKUP    SDLK_UP
#define BTSK_LOOKDOWN  SDLK_DOWN
#define BTSK_LOOKLEFT  SDLK_LEFT
#define BTSK_LOOKRIGHT SDLK_RIGHT
